kind: pipeline
name: greeting

steps:
- name: build
  image: alpine
  commands:
  - echo build

- name: test
  image: alpine
  commands:
  - echo test

- name: run
  image: alpine
  commands:
  - echo run
