kind: pipeline
name: greeting

steps:
- name: build
  image: python:3.7
  commands:
  - pip install pipenv
  - pipenv install

- name: run
  image: python:3.7
  commands:
  - pipenv run python app.py
